2020-02-06 02:36:54.554437: E tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:466] Unknown: Could not start gRPC server
Traceback (most recent call last):
  File &quot;linkedin/recruiterrelevance/train_listwise_model.py&quot;, line 307, in &lt;module&gt;
    starter.run(ListwiseModelRunner())
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/linkedin/tensorflowtraining/starter.py&quot;, line 30, in run
    executor.run(model, unparsed_args)
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/linkedin/tensorflowtraining/executor/TonYEstimatorExecutor.py&quot;, line 34, in run
    self.run_worker(tony_params, args)
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/linkedin/tensorflowtraining/executor/TonYEstimatorExecutor.py&quot;, line 87, in run_worker
    self.model.run_model(model_args)
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/linkedin/tensorflowtraining/basemodel/EstimatorBaseModel.py&quot;, line 65, in run_model
    self.run_tensorflow(args)
  File &quot;linkedin/recruiterrelevance/train_listwise_model.py&quot;, line 303, in run_tensorflow
    main(args)
  File &quot;linkedin/recruiterrelevance/train_listwise_model.py&quot;, line 242, in main
    tf.estimator.train_and_evaluate(model, train_spec, eval_spec)
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py&quot;, line 471, in train_and_evaluate
    return executor.run()
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py&quot;, line 638, in run
    getattr(self, task_to_run)()
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py&quot;, line 648, in run_worker
    return self._start_distributed_training()
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py&quot;, line 769, in _start_distributed_training
    self._start_std_server(config)
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py&quot;, line 757, in _start_std_server
    protocol=config.protocol)
  File &quot;cache/abcde/appcache/application_123456789568_34567/container_e42_123456789568_34567_01_000009/venv/Python/lib/python3.7/site-packages/tensorflow/python/training/server_lib.py&quot;, line 148, in __init__
    self._server = c_api.TF_NewServer(self._server_def.SerializeToString())
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server